Remove unused is_company reference in partner search from app connection
Lokavaluto/lokavaluto-addons pull request #179
Opened 2022-03-21 17:08 UTC by vaab

Signed-off-by: Valentin Lab <valentin.lab@kalysto.org>

2022-03-21 20:41 UTC, stephansainleger requested changes

2022-03-21 20:41 UTC, stephansainleger commented on lcc_lokavaluto_app_connection/services/partner_services.py
>          # NJ TODO: remove company data
remove comment

2022-03-23 14:39 UTC, vaab commented on lcc_lokavaluto_app_connection/services/partner_services.py
>          # NJ TODO: remove company data
thanks, saw it also.

2022-03-23 15:01 UTC, njeudy approved these changes
Ok for me :)

2022-03-28 13:12 UTC, stephansainleger approved these changes

2022-03-28 13:13 UTC, merged