[FIX] issue for la roue - June
Lokavaluto/lokavaluto-addons pull request #238
Opened 2022-06-26 14:12 UTC by njeudy

- fixes #237

2022-06-27 13:06 UTC, stephansainleger requested changes

2022-06-27 13:06 UTC, stephansainleger commented on lcc_members/__manifest__.py
> -        "wizard/membership_invoice_views.xml",
Why do you delete this line?

2022-06-27 13:06 UTC, stephansainleger commented on lcc_members/views/calendar_event_view.xml
> +        <record id="calendar_event_form_view" model="ir.ui.view">
Are we sure that the issue only occurs for calendar events. Don't we have the issue for each Many2one res.partner field ? If True, then I think we should find a more global solution.

2022-06-27 15:06 UTC, njeudy commented on lcc_members/views/calendar_event_view.xml
> +        <record id="calendar_event_form_view" model="ir.ui.view">
I can not imagine if it apply on all .. for now the probleme was calendar.event .. And it's ok for me . In fact I think we should'nt filter on main profile, because email can be different on différent profile .. I think user should know what they do .. :)

2022-06-27 15:08 UTC, njeudy commented on lcc_members/__manifest__.py
> -        "wizard/membership_invoice_views.xml",
you're right !

2022-07-01 06:39 UTC, stephansainleger approved these changes

2022-07-01 06:39 UTC, stephansainleger commented on lcc_members/views/calendar_event_view.xml
> +        <record id="calendar_event_form_view" model="ir.ui.view">
ok to remove only the public profiles

2022-07-01 06:39 UTC, merged